Fix preemption history snippet filter
googleapis/python-compute pull request #360
Opened 2022-11-07 22:18 UTC by fellhorn

The `:` operator seems perform a equality and not a substring match on the `targetLink` field. You can check the behavior with the [live API reference](https://cloud.google.com/compute/docs/reference/rest/v1/zoneOperations/list). Without this change `preemption_history` always returned an empty list when one provided an `instance_name`.

This might also seen as an API bug but the code snippet for preemption history can also be simplified this way.

2022-11-09 17:57 UTC, kurtisvg approved these changes

2022-11-23 17:38 UTC, parthea commented
```
=================================== FAILURES ===================================
________________________________ test_get_image ________________________________

self = <contextlib._GeneratorContextManager object at 0x7f3831d225f0>
typ = None, value = None, traceback = None

    def __exit__(self, typ, value, traceback):
        if typ is None:
            try:
>               next(self.gen)
E               AttributeError: 'SysCapture' object has no attribute '_old'

/usr/local/lib/python3.10/contextlib.py:142: AttributeError
```

2022-11-23 17:38 UTC, parthea requested changes
Samples Python 3.10 presubmit test is failing

2022-12-07 14:37 UTC, parthea commented
The samples have moved to [python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples)

2022-12-07 14:37 UTC, closed without merging